### ISSUE TITLE
JsGrid v1.4.1 not working with jQuery v2.2.4

### ISSUE THREAD

**Issue by eliasuardi** [tabalinas/jsgrid#290]
When I include jsGrid with jQuery v2.2.4 I see an error when opening a jQuery popup:

Uncaught TypeError: a.preventDefault is not a function

Is jsGrid v1.4.1 compatible with jQuery v2.2.4?
When are you planning to make it compatible?

Thank you.

**Comment by tabalinas** [comment]
jsGrid should be compatible with jQuery v2.2.4.
I believe it's an issue of concrete example implementation. Not sure what is `a` in your example.
The most interesting is mentioning of `jQuery popup`, it doesn't relate to js-grid, since grid depends only on jQuery (not jQuery UI).

**Comment by tabalinas** [comment]
I've tested jsGrid with jQuery v2.2.4 and it works just fine. Provide a jsfiddle with your example and reopen the issue if you still experience the issue.
